#!/usr/bin/python

from mod_pbxproj import *

frameworks = [
  'CoreTelephony.framework',
  'StoreKit.framework',
  'EventKit.framework',
  'MessageUI.framework',
  'AdSupport.framework'
]

pbx_file_path = sys.argv[1] + '/Unity-iPhone.xcodeproj/project.pbxproj'
pbx_object = XcodeProject.Load(pbx_file_path)

for framework in frameworks:
  pbx_object.add_file('System/Library/' + framework, tree='SDKROOT')

pbx_object.save()

# f = open('unity_build.log', 'w')
# for arg in sys.argv:
#   f.write(arg + '\n')

# f.close()
